# Generated by Django 5.1.7 on 2025-04-03 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribtion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprogress',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='enrollment_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='subscribtion.enrollment'),
        ),
    ]
