# Generated by Django 5.1.7 on 2025-04-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_quiz_answers_quiz_attempts_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='section',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
