# Generated by Django 5.1.7 on 2025-04-01 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_section_is_active_remove_topic_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz'),
        ),
    ]
